FROM node:20-alpine

WORKDIR /app

# Install native dependencies required for Nmap and traceroute
RUN apk update && \
    apk add --no-cache nmap nmap-scripts traceroute bind-tools iputils

# Install Node dependencies
COPY package*.json ./
RUN npm install

# Build the backend codebase
COPY . .
RUN npm run build

EXPOSE 5105

# Start the server
CMD ["npm", "run", "start:prod"]
